version: '3.9'
services:
  anemic:
    image: anemic-api:anemic
    ports:
      - 8080:8080
      - 9080:9080
  non-anemic:
    image: anemic-api:non-anemic
    ports:
      - 8080:8080
      - 9080:9080
